### ISSUE TITLE
Using SVG created by HighCharts, throws division by zero exception

### ISSUE THREAD

**Issue by ReLexEd** [PhenX/php-svg-lib#3]
Using HighCharts to display a chart, and fetching the SVG for it, posting it to the server, writing the data to a tmp-file, and referencing that in and img-tag.
(Tried inline as well, which does produce a PDF, but gives 'Image not found or type unknown' and a rectangle with a cross for each SVG)

ErrorException \vendor\phenx\php-svg-lib\src\Svg\Tag\Path.php line 448

Before the exception, there is also output generated:
`Unknown: 'desc' Unknown: 'clipPath' Unknown: 'desc' Unknown: 'clipPath' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'tspan' Unknown: 'desc' Unknown: 'clipPath'`

Svg content parsed:
`<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" style="font-family:'lucida grande', 'lucida sans unicode', arial, helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="600" height="400"><desc>Created with Highcharts 4.2.3</desc><defs><clipPath id="highcharts-47"><rect x="0" y="0" width="580" height="375"></rect></clipPath><radialGradient cx="0.5" cy="0.3" r="0.7" id="highcharts-48"><stop offset="0" stop-color="#7cb5ec" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(86,143,198)" stop-opacity="1"></stop></radialGradient><radialGradient cx="0.5" cy="0.3" r="0.7" id="highcharts-49"><stop offset="0" stop-color="#434348" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(29,29,34)" stop-opacity="1"></stop></radialGradient><radialGradient cx="0.5" cy="0.3" r="0.7" id="highcharts-50"><stop offset="0" stop-color="#90ed7d" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(106,199,87)" stop-opacity="1"></stop></radialGradient><radialGradient cx="0.5" cy="0.3" r="0.7" id="highcharts-51"><stop offset="0" stop-color="#f7a35c" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(209,125,54)" stop-opacity="1"></stop></radialGradient><radialGradient cx="290" cy="131.6" r="204.39999999999998" id="highcharts-52" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#7cb5ec" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(86,143,198)" stop-opacity="1"></stop></radialGradient><radialGradient cx="290" cy="131.6" r="204.39999999999998" id="highcharts-53" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#434348" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(29,29,34)" stop-opacity="1"></stop></radialGradient><radialGradient cx="290" cy="131.6" r="204.39999999999998" id="highcharts-54" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#90ed7d" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(106,199,87)" stop-opacity="1"></stop></radialGradient><radialGradient cx="290" cy="131.6" r="204.39999999999998" id="highcharts-55" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#f7a35c" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(209,125,54)" stop-opacity="1"></stop></radialGradient></defs><rect x="0" y="0" width="600" height="400" fill="#FFFFFF" class=" highcharts-background"></rect><g class="highcharts-series-group" ><g class="highcharts-series highcharts-series-0" transform="translate(10,10) scale(1 1)"><path fill="url(#highcharts-52)" d="M 289.97026371226053 44.00000302824253 A 146 146 0 1 1 228.95259141809078 57.37566623943616 L 290 190 A 0 0 0 1 0 290 190 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="url(#highcharts-53)" d="M 229.08524625344907 57.31468515319014 A 146 146 0 0 1 282.9379655680715 44.170895670026624 L 290 190 A 0 0 0 0 0 290 190 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="url(#highcharts-54)" d="M 283.0837981791136 44.16390655131781 A 146 146 0 0 1 286.29360708412884 44.04705329609416 L 290 190 A 0 0 0 0 0 290 190 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="url(#highcharts-55)" d="M 286.4395618597036 44.043419880263286 A 146 146 0 0 1 289.7972089290416 44.00014083643251 L 290 190 A 0 0 0 0 0 290 190 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path></g><g class="highcharts-markers highcharts-series-0" transform="translate(10,10) scale(1 1)"></g></g><g class="highcharts-data-labels highcharts-series-0" visibility="visible" transform="translate(10,10) scale(1 1)" opacity="1"><path fill="none" d="M 332.55154534011194 361.94732170804383 C 327.55154534011194 361.94732170804383 325.84465691556136 354.1315343576782 323.49768533180435 343.38482675092547 L 321.15071374804734 332.6381191441727" stroke="url(#highcharts-48)" stroke-width="1"></path><path fill="none" d="M 158.14575292880414 68 C 163.14575292880414 68 250.24477049852453 26.77156581255514 252.8477914777878 37.4591418605426 L 255.4508124570511 48.146717908530064" stroke="url(#highcharts-49)" stroke-width="1"></path><path fill="none" d="M 191.32503002402402 41 C 196.32503002402402 41 283.9808979914018 22.107860782554525 284.37500586101237 33.100798469411075 L 284.76911373062296 44.093736156267624" stroke="url(#highcharts-50)" stroke-width="1"></path><path fill="none" d="M 282.8976914147575 14 C 287.8976914147575 14 287.9932508959028 22.011985671497357 288.1246451824806 33.01120089538741 L 288.2560394690584 44.010416119277465" stroke="url(#highcharts-51)" stroke-width="1"></path><g style="cursor:pointer;" transform="translate(338,352)" class="highcharts-drilldown-data-label"><text x="5" style="font-size:11px;font-weight:bold;color:#0d233a;text-shadow:0 0 6px #ffffff, 0 0 3px #ffffff;fill:#0d233a;text-rendering:geometricprecision;text-decoration:underline;" y="16"><tspan>Internet Explorer</tspan></text></g><g style="cursor:pointer;" transform="translate(100,58)" class="highcharts-drilldown-data-label"><text x="5" style="font-size:11px;font-weight:bold;color:#0d233a;text-shadow:0 0 6px #ffffff, 0 0 3px #ffffff;fill:#0d233a;text-rendering:geometricprecision;text-decoration:underline;" y="16"><tspan>Chrome</tspan></text></g><g style="cursor:pointer;" transform="translate(138,31)" class="highcharts-drilldown-data-label"><text x="5" style="font-size:11px;font-weight:bold;color:#0d233a;text-shadow:0 0 6px #ffffff, 0 0 3px #ffffff;fill:#0d233a;text-rendering:geometricprecision;text-decoration:underline;" y="16"><tspan>Firefox</tspan></text></g><g style="cursor:pointer;" transform="translate(186,4)" class="highcharts-drilldown-data-label"><text x="5" style="font-size:11px;font-weight:bold;color:#0d233a;text-shadow:0 0 6px #ffffff, 0 0 3px #ffffff;fill:#0d233a;text-rendering:geometricprecision;text-decoration:underline;" y="16"><tspan>Microsoft Edge</tspan></text></g></g><g class="highcharts-legend" ><g ><g></g></g></g><g class="highcharts-tooltip" style="cursor:default;padding:0;pointer-events:none;white-space:nowrap;" transform="translate(0,-9999)"><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5" stroke="black" stroke-opacity="0.049999999999999996" stroke-width="5" transform="translate(1, 1)"></path><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5" stroke="black" stroke-opacity="0.09999999999999999" stroke-width="3" transform="translate(1, 1)"></path><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5" stroke="black" stroke-opacity="0.15" stroke-width="1" transform="translate(1, 1)"></path><path fill="rgb(249, 249, 249)" fill-opacity=" .85" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5"></path><text x="8" style="font-size:12px;color:#333333;fill:#333333;" y="20"></text></g></svg>`

**Comment by PhenX** [comment]
Hi, I don't have the same result with the master branch (no warning) and the SVG is rendered : 

![image](https://cloud.githubusercontent.com/assets/42170/13374204/1278731e-dd7e-11e5-8026-e11e9787721a.png)

Which version of PHP do you use ?

Gradients are not supported yet, so that's why every slice is black.

Do you use it via dompdf ?

**Comment by ReLexEd** [comment]
I'm using PHP5.6, and using DomPDF via barryvdh/laravel-dompdf, using the dev-master, so it pulls in dompdf-0.7-dev.

I'll look into it on monday a little further, to see if turning off the gradients from within HighCharts will give me results.

**Comment by ReLexEd** [comment]
Sorry, I now see, that when using a more simplified example, I do get output.
Looks like the problem lies in the wrapper I'm using.

**Comment by zxzzxxzx** [comment]
Hello,
I have got the same issue. When using more simplified svg file everything is ok, but if I use different one I get the same error message. Any ideas how to fix it? I may send you the files if it is needed.

**Comment by jeffwa** [comment]
I've been having the same issue as the original poster:

![1_zero_length_arcs_enabled](https://cloud.githubusercontent.com/assets/1898427/22022142/f8b488c6-dcc0-11e6-8561-6deef9763fd0.png)

It seems to be an issue where the arc is 0 length due to how it's generated by Highcharts. Adding the this code

`if (($toX + $toY) == 0) { return []; }`

as the first line of Svg\Tag\Path.php::arcToSegments() removes the offending segments:

![2_zero_length_arcs_ignored](https://cloud.githubusercontent.com/assets/1898427/22022141/f8b4032e-dcc0-11e6-91c4-8f38a77e2cd3.png)


SVG code: 
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" style="font-family:'lucida grande', 'lucida sans unicode', arial, helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="220" height="450"><defs><clipPath id="highcharts-29"><rect x="0" y="0" width="220" height="620"></rect></clipPath></defs><rect x="0" y="0" width="220" height="450" strokeWidth="0" fill="#FFFFFF" class=" highcharts-background"></rect><g class="highcharts-series-group" ><g class="highcharts-series highcharts-series-0" visibility="visible"  transform="translate(0,-180) scale(1 1)"><path fill="#BDCF31" d="M 109.97963267963048 210.0000020741387 A 100 100 0 0 1 135.30159047847422 213.25378808832056 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#84BCDA" d="M 135.39832402346735 213.27913804768406 A 100 100 0 0 1 146.70134010265588 216.97843457203493 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#BB342F" d="M 146.79434330191168 217.01518241679952 A 100 100 0 0 1 146.79434330191168 217.01518241679952 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#AE8E1C" d="M 146.8873097068273 217.05202324637398 A 100 100 0 0 1 154.0177483716293 220.20892122102595 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#F37748" d="M 154.10751742657072 220.25298385759692 A 100 100 0 0 1 166.1995474715555 227.28596936436733 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#067BC2" d="M 166.28223338863407 227.34221025948418 A 100 100 0 0 1 166.1995474715555 227.28596936436733 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#D56062" d="M 166.28223338863407 227.34221025948418 A 100 100 0 0 1 166.36486302348393 227.39853381238385 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#C5CBD3" d="M 166.44743629347548 227.45493996674284 A 100 100 0 0 1 200.8965749674885 268.31291975707893 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#8D6A9F" d="M 200.93821659249988 268.4038371604354 A 100 100 0 0 1 209.82600048314612 304.10342238761245 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#9B3D12" d="M 209.83184714677967 304.2032513197465 A 100 100 0 0 1 204.14131786897076 343.72554328537063 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#BDCF31" d="M 204.1075452606513 343.81966772477915 A 100 100 0 0 1 204.03971775526685 344.0078150505108 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#84BCDA" d="M 204.00566292602934 344.1018377486867 A 100 100 0 0 1 162.76199315484067 394.9480551768464 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#BB342F" d="M 162.67701873282746 395.00077468718354 A 100 100 0 0 1 155.09204621748086 399.2564135954418 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#AE8E1C" d="M 155.00276727274027 399.30146100594084 A 100 100 0 0 1 135.78500325326695 406.6184951612734 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#F37748" d="M 135.68837188170824 406.64423185098565 A 100 100 0 0 1 135.6883718817082 406.64423185098565 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#067BC2" d="M 135.59171482177973 406.66987189647404 A 100 100 0 0 1 123.63700755151447 409.0657964437774 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#D56062" d="M 123.53793495307846 409.079383916162 A 100 100 0 0 1 123.53793495307846 409.079383916162 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#C5CBD3" d="M 123.43884881670863 409.0928723091709 A 100 100 0 0 1 88.84078838438704 407.7358059454451 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#8D6A9F" d="M 88.74306317433583 407.7145978694572 A 100 100 0 0 1 79.0940771558335 405.10427925782534 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#9B3D12" d="M 78.99898834538654 405.0733257879965 A 100 100 0 0 1 11.315911101271496 293.83056592740957 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path><path fill="#BDCF31" d="M 11.332129874689514 293.73188993967455 A 100 100 0 0 1 109.86110200619284 210.00009646330994 L 110 310 A 0 0 0 0 0 110 310 Z" stroke="#FFFFFF" stroke-width="1" stroke-linejoin="round" transform="translate(0,0)"></path></g><g class="highcharts-markers highcharts-series-0" visibility="visible"  transform="translate(0,-180) scale(1 1)"></g></g><text x="110" text-anchor="middle" class="highcharts-title"  style="color:#666666;font-size:18px;font:bold 16px 'trebuchet ms', verdana, sans-serif;fill:#666666;width:176px;" y="14">Age</text><g class="highcharts-legend"  transform="translate(0,240)"><rect x="0.5" y="0.5" width="227" height="164" strokeWidth="1" rx="5" ry="5" stroke="#E7E7E7" stroke-width="1" fill="#FFFFFF" visibility="visible"></rect><g ><g><g class="highcharts-legend-item"  transform="translate(8,3)"><text x="21" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start"  y="15"><tspan>65+: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#BDCF31"></rect></g><g class="highcharts-legend-item"  transform="translate(118,3)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>65+: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#84BCDA"></rect></g><g class="highcharts-legend-item"  transform="translate(8,17)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>65+: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#BB342F"></rect></g><g class="highcharts-legend-item"  transform="translate(118,17)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>18 - 24: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#AE8E1C"></rect></g><g class="highcharts-legend-item"  transform="translate(8,31)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>18 - 24: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#F37748"></rect></g><g class="highcharts-legend-item"  transform="translate(118,31)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>18 - 24: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#067BC2"></rect></g><g class="highcharts-legend-item"  transform="translate(8,45)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>25 - 34: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#D56062"></rect></g><g class="highcharts-legend-item"  transform="translate(118,45)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>25 - 34: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#C5CBD3"></rect></g><g class="highcharts-legend-item"  transform="translate(8,59)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>25 - 34: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#8D6A9F"></rect></g><g class="highcharts-legend-item"  transform="translate(118,59)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>35 - 49: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#9B3D12"></rect></g><g class="highcharts-legend-item"  transform="translate(8,73)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>35 - 49: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#BDCF31"></rect></g><g class="highcharts-legend-item"  transform="translate(118,73)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>35 - 49: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#84BCDA"></rect></g><g class="highcharts-legend-item"  transform="translate(8,87)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>50 - 54: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#BB342F"></rect></g><g class="highcharts-legend-item"  transform="translate(118,87)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>50 - 54: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#AE8E1C"></rect></g><g class="highcharts-legend-item"  transform="translate(8,101)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>50 - 54: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#F37748"></rect></g><g class="highcharts-legend-item"  transform="translate(118,101)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>55 - 64: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#067BC2"></rect></g><g class="highcharts-legend-item"  transform="translate(8,115)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>55 - 64: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#D56062"></rect></g><g class="highcharts-legend-item"  transform="translate(118,115)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>55 - 64: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#C5CBD3"></rect></g><g class="highcharts-legend-item"  transform="translate(8,129)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>Unknown: Unknown</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#8D6A9F"></rect></g><g class="highcharts-legend-item"  transform="translate(118,129)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>Unknown: Dutch</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#9B3D12"></rect></g><g class="highcharts-legend-item"  transform="translate(8,143)"><text x="21" y="15" style="color:#666;font-size:12px;font-weight:bold;cursor:pointer;font:9pt 'trebuchet ms', verdana, sans-serif;fill:#666;" text-anchor="start" ><tspan>Unknown: French</tspan></text><rect x="0" y="4" width="16" height="12"  fill="#BDCF31"></rect></g></g></g></g><g class="highcharts-tooltip"  style="cursor:default;padding:0;pointer-events:none;white-space:nowrap;" transform="translate(0,-9999)"><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5"  stroke="black" stroke-opacity="0.049999999999999996" stroke-width="5" transform="translate(1, 1)"></path><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5"  stroke="black" stroke-opacity="0.09999999999999999" stroke-width="3" transform="translate(1, 1)"></path><path fill="none" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5"  stroke="black" stroke-opacity="0.15" stroke-width="1" transform="translate(1, 1)"></path><path fill="rgb(249, 249, 249)" fill-opacity=" .85" d="M 3.5 0.5 L 13.5 0.5 C 16.5 0.5 16.5 0.5 16.5 3.5 L 16.5 13.5 C 16.5 16.5 16.5 16.5 13.5 16.5 L 3.5 16.5 C 0.5 16.5 0.5 16.5 0.5 13.5 L 0.5 3.5 C 0.5 0.5 0.5 0.5 3.5 0.5"></path><text x="8"  style="font-size:12px;color:#333333;fill:#333333;" y="20"></text></g></svg>`

**Comment by MilinkoDragovic** [comment]
Having the same error, when trying to export pdf with laravel-dompdf. I have exported SVG Highcharts charts(Bars, Line, Pie etc.),  but displaying them inside pdf gives me an error "Division by zero".
